- name: copy logstash repo file
  ansible.builtin.template:
    src: logstash.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: install logstash
  ansible.builtin.dnf:
    name: logstash
    state: installed

- name: pass frontend logs to kibana
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/conf.d/logstash.conf

- name: restart logstash service
  ansible.builtin.systemd_service:
    name: logstash
    state: started

