- name: get secrets
  hosts: localhost
  tasks:
    - name: get vault secrets
      ansible.builtin.lineinfile:
        path: ~/{{item | split('/') | last}}.json
        line: "{{ lookup('hashi_vault', 'secret={{item}}  token={{vault_token}} url=https://vault-internal.pdevops72.online:8200 validate_certs=False')}}"
        create: yes
      loop:
        - common/data/vault_secret
        - expense-{{env}}/data/{{component_name}}
        - common/rds

# *.json will store in home directory , loop all json files and store in one json files

    - name: loop all json files
      ansible.builtin.shell: for i in ~/*.json; do echo $(cat $i) done > secrets.json

