- name: remove a directory
  ansible.builtin.file:
    path: /opt/node_exporter
    state: absent
    owner: bin
    group: bin

- name: make a directory
  ansible.builtin.file:
    path: /opt/node_exporter
    state: directory
    owner: bin
    group: bin

- name: Download and unarchive node_exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{version}}/node_exporter-{{version}}.linux-amd64.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    owner: bin
    group: bin

- name: copy node_exporter service
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter Server
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    daemon_reload: true
    enabled: true
